modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/ThEWiZ76/NeoOpenComputers/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/ThEWiZ76/NeoOpenComputers"
credits="Based on MightyPirates/OpenComputers."
authors="NeoOpenComputers community"
description='''
NeoOpenComputers is a community-maintained Java-first NeoForge port of
OpenComputers for Minecraft 1.21.1.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
