# This file contains bundled read-only floppy disk descriptors.
# Format: folder=label:weight:dyeOreName
network=Network (Network Stack):1:dyeLime
plan9k=Plan9k (Operating System):1:dyeRed
irc=OpenIRC (IRC Client):1:dyeLightBlue
openloader=OpenLoader (Boot Loader):1:dyeMagenta
openos=OpenOS (Operating System):0:dyeGreen
oppm=OPPM (Package Manager):0:dyeCyan
builder=Builder:1:dyeYellow
dig=Digger:2:dyeBrown
maze=Mazer:1:dyeOrange
data=Data Card Software:0:dyePink
generator=Generator Upgrade Software:0:dyePurple
